- name: Deploy Django framework
  hosts:
    - class_webservices
    
  gather_facts: false
  
  vars_files:
    - variables/vars.yml
    - variables/provision.yml
          
  pre_tasks:
  
    - name: 'Get datacenter.json content'
      set_fact:
        datacenter_config: "{{ lookup('file', '{{ messageboard_dir }}/config/datacenter.json') | from_json }}"
        
    - name: 'Get instance DNS domain'
      set_fact:
        instance_dns_domain: "{{ datacenter_config | json_query(jquery) }}"
      vars:
        jquery: "Datacenter.Instances[?Name=='{{ instance_name }}'] | [0].DnsDomain"     

    - name: 'Controller host configuration'
      ansible.builtin.debug:
        msg:
          - 'SSH port: {{ ansible_port }}'
          - 'SSH user: {{ ansible_user }}'
          - 'SSH key: {{ ansible_private_key_file }}'
          - 'AWS instance domain: {{ instance_dns_domain }}'
          - 'Django project name: {{ aws.instance.project.django.name }}' 
          - 'Django super user name: {{ aws.instance.project.django.superuser.name }}' 
          - 'Django super user email address: {{ aws.instance.project.django.superuser.email.address }}' 
                 
    - name: Delete download directory
      become: true
      ansible.builtin.file:
        path: "{{ aws.instance.download.dir.path }}"
        state: absent       
                  
  tasks:
   
    - name: Create download directory
      become: true
      ansible.builtin.file:
        path: "{{ aws.instance.download.dir.path }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 488        
             
    - name: Get the project from Github (with agent forwarding)
      become: false
      ansible.builtin.git:
        repo: "{{ aws.instance.project.django.github.repository.url }}"
        dest: "{{ aws.instance.download.dir.path }}"
        version: master
        accept_hostkey: true
        update: false
 
    - name: Delete project directory
      become: true
      ansible.builtin.file:
        path: "{{ aws.instance.project.django.dir.path }}"
        state: absent 
        
    - name: Create project directory
      become: true
      ansible.builtin.file:
        path: "{{ aws.instance.project.django.dir.path }}"
        state: directory               
 
    - name: Copy project files
      become: true
      ansible.builtin.command: "mv {{ item }} {{ aws.instance.project.django.dir.path }}"
      with_items:
      - "{{ aws.instance.download.dir.path }}/project/manage.py"
      - "{{ aws.instance.download.dir.path }}/project/{{ aws.instance.project.django.name }}" 
      - "{{ aws.instance.download.dir.path }}/project/apps" 
      - "{{ aws.instance.download.dir.path }}/project/templates" 
      
    - name: Copy Django settings.py file
      become: true
      ansible.builtin.template:
        src: django/settings.py.j2
        dest: "{{ aws.instance.project.django.dir.path }}/{{ aws.instance.project.django.name }}/settings.py"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 488 
        
    - name: Copy Django environment file
      become: true
      ansible.builtin.template:
        src: django/env.j2
        dest: "{{ aws.instance.project.django.dir.path }}/.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0400                
      
    - name: Run database migrations
      community.general.django_manage:
        command: migrate
        project_path: "{{ aws.instance.project.django.dir.path }}"  
        virtualenv: "{{ aws.instance.project.django.venv.dir.path }}"
      environment:   
        DATABASE_URL: "{{ aws.instance.postgresql.database.url }}"      

    - name: Collect static files
      become: true
      community.general.django_manage:
        command: collectstatic
        project_path: "{{ aws.instance.project.django.dir.path }}"  
        virtualenv: "{{ aws.instance.project.django.venv.dir.path }}"                  
      
    - name: Restart Gunicorn
      become: true 
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        enabled: true
        name: gunicorn
   
    - name: Restart Nginx
      become: true 
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: nginx
    
    - name: 'Test it: https://{{ instance_dns_domain }}:{{ aws.instance.nginx.https.port }}/admin'
      become: false  
      ansible.builtin.uri:
        url: 'https://{{ instance_dns_domain }}:{{ aws.instance.nginx.https.port }}/admin'
        method: GET
        status_code: 200
        validate_certs: false
        return_content: true
      register: result
      failed_when: "'Django site admin' not in result.content"    
      
    - name: 'Test it: https://{{ instance_dns_domain }}:{{ aws.instance.nginx.https.port }}'
      become: false  
      ansible.builtin.uri:
        url: 'https://{{ instance_dns_domain }}:{{ aws.instance.nginx.https.port }}'
        method: GET
        status_code: 200
        validate_certs: false
        return_content: true
      register: result
      failed_when: "'Message board posts' not in result.content"          
          
  post_tasks:
  
    - name: Delete download directory
      become: true
      ansible.builtin.file:
        path: "{{ aws.instance.download.dir.path }}"
        state: absent 
         
