- name: Installs common programs
  hosts:
    - all
  gather_facts: false
  
  vars_files:
    - variables/vars.yml
    - variables/aws.yml
    - variables/secrets.yml
    
  pre_tasks:
      
    - name: 'Controller host configuration (magic variables)'
      ansible.builtin.debug:
        msg:
        - "domain: {{ instance_dns_domain }}"
        - "ssh port: {{ ansible_port }}"
        - "ssh user: {{ ansible_user }}"
        - "ssh key: {{ ansible_ssh_private_key_file }}"
    
  tasks:
    - name: update yum cache
      ansible.builtin.yum: update_cache=true
  
    - name: upgrade all packages
      ansible.builtin.yum: name=* state=latest 
                         
    - name: Install a list of packages 
      ansible.builtin.yum:
        name:
          - supervisor
          - git
          - vim         
        state: present
        