---

aws:
  instance: 
    download:
      dir:
        path: /opt/download  
    programs:
      install:
        dir:
          path: /opt   
    java:
      version: "18.0.2.1" 
      root:
        dir: 
          name: "jdk-18.0.2.1"                   
    tomcat:
      version: "10.1.23"           
      root:
        dir:
          name: apache-tomcat-10.1.23                
      http:
        port: "8080"
      https:
        port: "8443"              
    python:
      version: "3.11.4"   
      install:
        dir:
          path: /usr/local/bin   
      executable: "python3.11"
    openssl:
      version: "1.1.1u"
    nginx:
      install:
         dir:
           path: "/etc/nginx"
      root:
        dir:
          path: "/usr/share/nginx/html"           
      tls:
        dir:
          path: "/etc/nginx/ssl/"
        key:
          file: "nginx.key"
        cert:
          file: "nginx.crt"
      http:
        port: "8080"
      https:
        port: "8443"      
    postgresql:
      version: "14"
      database:
        name: "postgresqldb"
        connection:
          url: "postgres://{{ postgresql_admin_user_name }}:{{ postgresql_admin_user_password }}@localhost/postgresqldb"
    gunicorn:
       config:
         dir:
           path: "/opt/gunicorn"   
       socket:
         file: 
           path: "/etc/systemd/system/gunicorn.socket"               
       systemd:
         socket:
           file: 
             path: "/etc/systemd/system/gunicorn.socket"       
    project:
      root:
        dir:
          name: "messageboard"
      venv:
        dir:
          path: "/opt/.venv"
      superuser:
        name: "{{ django_superuser_name }}"
        email:
          address: '{{ django_superuser_email_address }}'
      github:
        repository:
          url: git@github.com:maxmin13/messageboard-prj.git
          
...
