---

aws:
  instance: 
    download:
      dir:
        path: /opt/download    
    python:
      install:
        dir:
          path: /usr/local/bin
      executable: "{{ python_executable }}"
      version: "{{ python_version }}"  
    postgresql:
        version: "{{ postgresql_version }}"
        superuser: '{{ postgresql_superuser }}'
        database:
          url: "postgres://{{ postgresql_admin_user_name }}:{{ postgresql_admin_user_password }}@localhost/{{ postgresql_database_name }}"
          name: "{{ postgresql_database_name }}"
          user:
            admin: 
              name: "{{ postgresql_admin_user_name }}"  
          service:
            name: 'postgresql-{{ postgresql_version }}'  
    gunicorn:
       config:
         file:
           path: "/opt/gunicorn"
       socket:
         file: 
           path: "/etc/systemd/system/gunicorn.socket"     
       service:
         file:
           path: "/etc/systemd/system/gunicorn.service" 
    nginx:
      install:
         dir:
           path: "/etc/nginx"
      config:
        file: '/etc/nginx/nginx.conf'
      tls:
        dir:
          path: "/etc/nginx/ssl"
      key:
        file: "nginx.key"
      cert:
        file: "nginx.crt"
      root:
        dir:
          path: "/usr/share/nginx/html"
      https:
        port: "8443"            
    project:
      django:
        name: "{{ django_project_name }}"
        dir:
          path: "/opt/messagebaord"
        venv:
          dir:
            path: "/opt/.venv"
        superuser:
          name: "{{ django_superuser_name }}"
          email:
            address: '{{ django_superuser_email_address }}'
        github:
          repository:
            url: git@github.com:maxmin13/messageboard-prj.git
...