plugin: aws_ec2
keyed_groups:
  - key: tags.name
    prefix: name
  - key: tags.class
    prefix: class
  - key: tags.database
    prefix: database 
  - key: tags.webserver
    prefix: webserver  
  - key: tags.common
    prefix: common    
  - key: tags.jdk
    prefix: jdk                 
filters:
  instance-state-name: running
compose:
  ansible_host: public_ip_address